name: CI
on: [push]
jobs:
  Run-Test-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install all dependencies
        run: |
          pip install -r requirements.txt
      - name: Run all test cases
        run: |
          pytest -s -v tests
      - run: echo "ğŸ This job's status is ${{ job.status }}."